Initialize
agnosticful/daddy-backend pull request #2
Opened 2019-02-19 23:08 UTC by ryotogashi

Can you review the changes?

2019-02-19 23:31 UTC, axross submitted a review, later dismissed
![LGTM](https://user-images.githubusercontent.com/4289883/53055108-6f91b880-345b-11e9-92d4-7906ab708778.png)

Request you to put server code with micro in the next pull request.

2019-02-19 23:31 UTC, axross commented on .gitignore
> +// compiled file dir
Use `#` instead

2019-02-19 23:31 UTC, axross commented on app.yaml
> +runtime: nodejs8
Prefer to use Node v10 instead

2019-02-19 23:31 UTC, axross commented on package.json
> +  "version": "1.0.0",
Set version `0.0.0`

2019-02-19 23:31 UTC, axross commented on package.json
> +  "license": "MIT",
Do not put any license

2019-02-19 23:39 UTC, ryotogashi commented
@axross Can you check again? I modified the result of the review.

2019-02-20 00:27 UTC, axross requested changes
🐧

2019-02-20 00:27 UTC, axross commented on package.json
> +  "license": "",
Remove `license` field itself

2019-02-20 19:06 UTC, ryotogashi commented on package.json
> +  "license": "",
@axross Removed license field.

2019-02-20 19:08 UTC, axross commented on package.json
> +    "graphql-tools": "^4.0.4"
There's several dependencies added than before. Is this a mistake?

2019-02-21 04:07 UTC, ryotogashi commented
@axross Can you check again? I modified the result of the review.

2019-02-21 04:35 UTC, axross commented on package.json
> +  "main": "built/main.js",
```suggestion

```

2019-02-21 04:35 UTC, axross commented on package.json
> +  }
Delete empty `"devDependencies"` and `"dependencies"` sections.

2019-02-21 04:46 UTC, axross approved these changes
![LGTM](https://user-images.githubusercontent.com/4289883/53144307-98e04080-3550-11e9-8d78-70f8c64d5fd7.png)

2019-02-21 04:48 UTC, merged