Add hello world with graphql
agnosticful/daddy-backend pull request #8
Opened 2019-03-05 07:33 UTC by ryotogashi

@axross Can you check?

2019-03-05 23:37 UTC, axross requested changes
LGTM, but there's few thing to be fixed.

2019-03-05 23:37 UTC, axross commented on package.json
> +    "@types/graphql": "^14.0.7",
This is supposed to be in `devDependencies`.

2019-03-05 23:37 UTC, axross commented on package.json
> +    "http": "0.0.0",
Where do you use `http` package in?

2019-03-05 23:37 UTC, axross commented on src/main.ts
> +    if (searchParams.has("query")) {
You should concat these three conditions into one if statement.

2019-03-06 01:45 UTC, ryonryon reviewed
@axross I changed the result of your review. Can you check it again?

2019-03-06 03:31 UTC, ryotogashi commented
@axross test passed now. Can you check again?

2019-03-06 04:39 UTC, axross commented
Test has still been failed. Maybe you missed to close an ad-hoc server in the test code.

2019-03-06 06:16 UTC, ryotogashi commented
@axross  I got it!

2019-03-06 22:37 UTC, axross approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/10827)

2019-03-06 22:37 UTC, axross commented on src/__tests__/main-test.ts
> +  test("responds graphql data", async () => {
I think this is much better

```suggestion
  test("responds data through graphql", async () => {
```

2019-03-06 22:37 UTC, axross commented on src/main.ts
> +  },
You can omit block `{}` and `return` statement.

```ts
  hello: () => 'Hello world!',
```

2019-03-07 01:23 UTC, merged